# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright 2025 John Wharington jwharington@gmail.com


from os import path

import FreeCADGui
from pivy import coin


def find_child(node, type_name):
    children = node.getChildren()

    if children is None or children.getLength() == 0:
        return None

    for child in children:
        if child.getTypeId().getName() == type_name:
            return child

    return None


def has_child(node, type_name):
    children = node.getChildren()

    if children is None or children.getLength() == 0:
        return None

    for child in children:
        if child.getTypeId().getName() == type_name:
            return node

        res = has_child(child, type_name)
        if res is not None:
            return res

    return None


def remove_by_name(node, name):
    item = node.getByName(name)
    if item:
        node.removeChild(item)
        return True
    return False


class MeshGridShader:
    shaderpath = path.dirname(path.abspath(__file__))

    def __init__(self):
        self.x_scale = coin.SoShaderParameter1f()
        self.x_scale.name = "x_scale"
        self.y_scale = coin.SoShaderParameter1f()
        self.y_scale.name = "y_scale"
        self.z_scale = coin.SoShaderParameter1f()
        self.z_scale.name = "z_scale"
        self.darken = coin.SoShaderParameter1f()
        self.darken.name = "darken"

        # Track whether self.texcoords has been added to self.grp
        self._texcoords_attached = False

        # Spacing in UV units (mm on the draped surface).
        # UV ranges: u≈[-105,105] (210), v≈[-650,650] (1300).
        # With spacing 5: scale=0.2 → coord≈0.2*105=21 → ~21 grid lines.
        self.Spacing = [5.0, 5.0, 5.0]
        self.Darken = 0.1

        shader_params = [
            self.x_scale,
            self.y_scale,
            self.z_scale,
            self.darken,
        ]

        self.fragmentShader = coin.SoFragmentShader()
        self.fragmentShader.sourceProgram.setValue(
            path.join(MeshGridShader.shaderpath, "Grid_fragment_shader.glsl")
        )
        self.fragmentShader.parameter.setValues(
            0,
            len(shader_params),
            shader_params,
        )
        self.shaderProgram = coin.SoShaderProgram()
        self.shaderProgram.shaderObject.set1Value(0, self.fragmentShader)
        self.shaderProgram.setName("my_shader")

        # Transform applied to texture coordinates generated by
        # SoTextureCoordinate3.  Used to rotate the grid by the rosette angle.
        self.tex_matrix_transform = coin.SoTextureMatrixTransform()
        self.tex_matrix_transform.matrix.setValue(
            1, 0, 0, 0,
            0, 1, 0, 0,
            0, 0, 1, 0,
            0, 0, 0, 1,
        )

        self.grp = coin.SoGroup()

    @property
    def Spacing(self):
        return [
            1.0 / self.x_scale.value.getValue(),
            1.0 / self.y_scale.value.getValue(),
            1.0 / self.z_scale.value.getValue(),
        ]

    @Spacing.setter
    def Spacing(self, v):
        self.x_scale.value = 1.0 / v[0]
        self.y_scale.value = 1.0 / v[1]
        self.z_scale.value = 1.0 / v[2]

    @property
    def Darken(self):
        return self.darken.value.getValue()

    @Darken.setter
    def Darken(self, v):
        self.darken.value = v

    @property
    def Root(self):
        return self.root

    def getTextureCoords(self, tex_coords):
        # SoTextureCoordinate3 generates texture coordinates from the
        # 3D positions of vertices.  It is a STATE node that sets
        # gl_TexCoord[0] in the scene graph, which the fragment shader
        # reads.  We populate the point array as metadata (unused by
        # the generator itself) so that the geometry's textureCoordIndex
        # mapping still works when we later switch to explicit coords.
        textureCoords = coin.SoTextureCoordinate3()
        textureCoords.setName("my_texcoord")
        if tex_coords is not None:
            for index, pt in enumerate(tex_coords):
                if len(pt) >= 3:
                    s, t, q = pt[0], pt[1], pt[2]
                else:
                    s, t = pt[0], pt[1]
                    q = 0.0
                textureCoords.point.set1Value(index, s, t, q)
        return textureCoords

    def detach(self, obj=None):
        """Detach the shader from the scene graph.

        Removes any previously attached texcoords and root nodes from self.grp.
        Idempotent -- safe to call multiple times.
        """
        self._cleanup()
        self.attach(obj, None, None)

    def _cleanup(self):
        """Remove all dynamically-added nodes from self.grp.

        Counterpart to the addChild calls in attach(). Safe to call even if
        nothing was ever attached -- acts as a no-op in that case.
        """
        if self._texcoords_attached and hasattr(self, "texcoords"):
            try:
                self.grp.removeChild(self.texcoords)
            except Exception:
                pass
            self._texcoords_attached = False
        if hasattr(self, "coord_binding"):
            try:
                self.grp.removeChild(self.coord_binding)
            except Exception:
                pass
        if hasattr(self, "tex_matrix_transform"):
            try:
                self.grp.removeChild(self.tex_matrix_transform)
            except Exception:
                pass
        if hasattr(self, "shaderProgram"):
            try:
                self.grp.removeChild(self.shaderProgram)
            except Exception:
                pass

    def attach(self, obj, child, tex_coords=None, offset_angle_deg=0):
        # Clean up old nodes FIRST, before creating new ones.
        self._cleanup()
        if hasattr(self, "root") and self.root is not None:
            remove_by_name(self.grp, self.root.getName())
            # Also remove shader nodes inserted into the old root
            self._remove_shader_from_root()

        if tex_coords is None:
            return

        self.texcoords = self.getTextureCoords(tex_coords)

        # Apply rosette angle as a 2D rotation in the UV plane.
        if offset_angle_deg:
            import math
            ang = math.radians(-offset_angle_deg)
            cos_a, sin_a = math.cos(ang), math.sin(ang)
            self.tex_matrix_transform.matrix.setValue(
                cos_a, -sin_a, 0, 0,
                sin_a,  cos_a, 0, 0,
                0,      0,     1, 0,
                0,      0,     0, 1,
            )
        else:
            self.tex_matrix_transform.matrix.setValue(
                1, 0, 0, 0,
                0, 1, 0, 0,
                0, 0, 1, 0,
                0, 0, 0, 1,
            )

        # Get the DrapeMesh root node (SoFCSelectionRoot, inherits SoSeparator).
        # We must insert the shader nodes INSIDE this separator, right before
        # the Separator that contains the geometry.  Setting the shader as a
        # sibling BEFORE the separator doesn't work — the separator saves
        # and restores GL state, overriding our shader.
        self.root = child.ViewObject.RootNode

        # Find the Switch child inside the root that contains the geometry.
        # The mesh geometry (SoFCIndexedFaceSet) is inside this Switch.
        # The shader must be inserted BEFORE this Switch so it's set before
        # the geometry is rendered during scene graph traversal.
        root_children = self.root.getChildren()
        switch_index = -1
        if root_children:
            for i in range(root_children.getLength()):
                c = root_children[i]
                if str(c.getTypeId().getName()) == "Switch":
                    switch_index = i
                    break

        if switch_index >= 0:
            # Insert shader nodes BEFORE the Switch, inside the root
            self.root.insertChild(self.texcoords, switch_index)
            self.root.insertChild(self.tex_matrix_transform, switch_index)
            self.root.insertChild(self.shaderProgram, switch_index)
            self._shader_in_root = True
        else:
            # Fallback: add to grp as before
            self.grp.addChild(self.shaderProgram)
            self.grp.addChild(self.tex_matrix_transform)
            self.grp.addChild(self.texcoords)
            self._texcoords_attached = True
            self.grp.addChild(self.root)

        self._texcoords_attached = True

        # Set textureCoordIndex on the geometry
        type_name = "SoFCIndexedFaceSet"
        node = has_child(self.root, type_name)
        geom = find_child(node, type_name)
        if geom:
            coordinateIndex = geom.coordIndex.getValues()
            geom.textureCoordIndex.setValues(
                0,
                len(coordinateIndex),
                coordinateIndex,
            )

        # Move the root from the scene graph into our display-mode group
        doc = obj.Document
        doc = FreeCADGui.getDocument(doc.Name)
        graph = doc.ActiveView.getSceneGraph()
        try:
            graph.removeChild(self.root)
        except Exception:
            pass  # Already moved or not a direct child
        self.grp.addChild(self.root)

    def _remove_shader_from_root(self):
        """Remove shader nodes inserted into the DrapeMesh root."""
        if not getattr(self, "_shader_in_root", False):
            return
        if not hasattr(self, "root") or self.root is None:
            self._shader_in_root = False
            return
        for node in [self.shaderProgram, self.tex_matrix_transform, self.texcoords]:
            try:
                self.root.removeChild(node)
            except Exception:
                pass
        self._shader_in_root = False
